export const strings = {
  appName: 'maddyBio 🌸',
  appSubtitle: 'صفحه‌ساز لینک در بایو فارسی',
  editor: 'ویرایشگر',
  preview: 'پیش‌نمایش',
  addBlock: 'افزودن بلوک',
  download: 'دانلود صفحه 🚀',
  downloadSuccess: 'فایل با موفقیت ساخته شد! 🎉',
  publishGuide: 'راهنمای انتشار',
  settings: 'تنظیمات',
  themes: 'قالب‌ها',
  undo: 'بازگشت',
  redo: 'بازگشت به جلو',
  reset: 'شروع دوباره',
  resetConfirm: 'آیا از حذف همه تغییرات مطمئن هستید؟',
  exportProject: 'خروجی پروژه (JSON)',
  importProject: 'ورودی پروژه (JSON)',
  importSuccess: 'پروژه با موفقیت بارگذاری شد',
  noProject: 'هیچ پروژه‌ای یافت نشد',
  newProject: 'پروژه جدید',
  projectName: 'اسم صفحه',
  projectNamePlaceholder: 'مثلاً: صفحه من',
  save: 'ذخیره',
  cancel: 'لغو',
  confirm: 'تأیید',
  delete: 'حذف',
  duplicate: 'کپی',
  enabled: 'فعال',
  disabled: 'غیرفعال',
  dragHandle: 'جابه‌جایی',

  profile: {
    title: 'پروفایل',
    avatar: 'عکس پروفایل',
    uploadAvatar: 'آپلود عکس',
    name: 'نام نمایشی',
    namePlaceholder: 'نام خود را وارد کنید',
    bio: 'بیو (حداکثر ۱۵۰ کاراکتر)',
    bioPlaceholder: 'توضیح کوتاه درباره خود...',
    avatarShape: 'شکل آواتار',
    circle: 'دایره',
    squircle: 'اسکواکل',
    flower: 'گل 🌸',
    charCount: '{count}/۱۵۰',
  },

  link: {
    title: 'دکمه لینک',
    buttonTitle: 'عنوان دکمه',
    buttonTitlePlaceholder: 'مثلاً: وبسایت من',
    url: 'آدرس لینک',
    urlPlaceholder: 'https://...',
    icon: 'آیکون',
    special: 'لینک ویژه ✨',
    newTab: 'باز شدن در تب جدید',
    style: 'استایل دکمه',
    solid: 'پُر',
    outline: 'خطی',
    shadow: 'سایه‌دار',
    gradient: 'گرادیانت',
  },

  social: {
    title: 'شبکه‌های اجتماعی',
    instagram: 'اینستاگرام',
    telegram: 'تلگرام',
    whatsapp: 'واتساپ',
    eitaa: 'ایتا',
    bale: 'بله',
    rubika: 'روبیکا',
    youtube: 'یوتیوب',
    linkedin: 'لینکدین',
    github: 'گیت‌هاب',
    email: 'ایمیل',
    phone: 'تلفن',
    usernamePlaceholder: 'آیدی یا شماره',
    phoneHint: 'مثال: 09123456789',
  },

  card: {
    title: 'شماره کارت / شبا 💳',
    cardNumber: 'شماره کارت',
    cardNumberPlaceholder: 'XXXX-XXXX-XXXX-XXXX',
    shaba: 'شماره شبا',
    shabaPlaceholder: 'IRXXXXXXXXXXXXXXX',
    accountHolder: 'نام صاحب حساب',
    accountHolderPlaceholder: 'نام و نام خانوادگی',
    bankName: 'نام بانک',
    cardDetected: 'تشخیص داده شد: {bank}',
    copyCard: 'کپی شماره کارت 📋',
    copied: 'کپی شد! ✅',
    invalidCard: 'شماره کارت نامعتبر',
    invalidShaba: 'شماره شبا نامعتبر',
  },

  text: {
    title: 'متن',
    content: 'متن',
    contentPlaceholder: 'متن خود را بنویسید...',
    fontSize: 'سایز قلم',
    small: 'کوچک',
    medium: 'متوسط',
    large: 'بزرگ',
    alignment: 'تراز',
    right: 'راست',
    center: 'وسط',
    left: 'چپ',
  },

  image: {
    title: 'تصویر / بنر',
    upload: 'آپلود تصویر',
    borderRadius: 'گردی گوشه',
    link: 'لینک روی تصویر (اختیاری)',
    linkPlaceholder: 'https://...',
  },

  video: {
    title: 'ویدیو',
    platform: 'پلتفرم',
    aparat: 'آپارات',
    youtube: 'یوتیوب',
    url: 'لینک ویدیو',
    urlPlaceholder: 'https://aparat.com/v/...',
  },

  divider: {
    title: 'جداکننده',
    line: 'خط ساده',
    dashed: 'نقطه‌چین',
    icon: 'با آیکون',
    iconPlaceholder: 'آیکون (مثلاً 🌸)',
  },

  qr: {
    title: 'QR Code',
    url: 'آدرس صفحه',
    urlPlaceholder: 'https://mypage.com',
  },

  theme: {
    title: 'قالب صفحه',
    customize: 'شخصی‌سازی',
    primaryColor: 'رنگ اصلی',
    background: 'پس‌زمینه',
    gradient: 'گرادیانت',
    solid: 'رنگ تخت',
    image: 'تصویر',
    buttonShape: 'شکل دکمه‌ها',
    round: 'گرد کامل',
    semiRound: 'نیمه‌گرد',
    sharp: 'تیز',
    fontSize: 'سایز فونت',
    small: 'کوچک',
    medium: 'متوسط',
    large: 'بزرگ',
    uploadBg: 'آپلود تصویر پس‌زمینه',
    showFooter: 'نمایش «ساخته‌شده با maddyBio» در فوتر',
    suggestedColors: 'رنگ‌های پیشنهادی',
  },

  publish: {
    title: 'راهنمای انتشار 📤',
    subtitle: 'فایل HTML دانلود شد. حالا چطور منتشرش کنم؟',
    tab1: 'GitHub Pages',
    tab2: 'Netlify Drop',
    tab3: 'هاست شخصی',
    step1: 'یک ریپازیتوری جدید در github.com ایجاد کنید',
    step2: 'فایل index.html را آپلود کنید',
    step3: 'از تب Settings > Pages منبع را روی main قرار دهید',
    step4: 'لینک https://{username}.github.io/{repo} را کپی کنید',
    netlifyStep1: 'به netlify.app بروید و وارد شوید',
    netlifyStep2: 'فایل index.html را به بخش Drop بکشید',
    netlifyStep3: 'چند ثانیه صبر کنید تا صفحه منتشر شود',
    netlifyStep4: 'لینک اختصاصی خود را دریافت کنید',
    hostStep1: 'فایل index.html را دانلود کنید',
    hostStep2: 'از طریق FTP یا cPanel به هاست خود متصل شوید',
    hostStep3: 'فایل را در پوشه public_html آپلود کنید',
    hostStep4: 'لینک دامنه خود را باز کنید',
  },

  darkMode: 'حالت تاریک',
  lightMode: 'حالت روشن',
  madeWith: 'ساخته‌شده با',
}
