import type { PageTemplate, Block } from '../types'
import { generateId } from '../lib/utils'

export const templates: PageTemplate[] = [
  {
    id: 'freelancer',
    name: 'فریلنسر',
    icon: '💻',
    description: 'مناسب طراحان، توسعه‌دهندگان و فریلنسرها',
    paletteId: 'blossom',
    blocks: [
      {
        id: generateId(),
        type: 'profile',
        enabled: true,
        avatar: '',
        avatarShape: 'circle',
        name: 'سارا محمدی',
        title: 'طراح تجربه کاربری',
        bio: 'تخصص در طراحی محصولات دیجیتال با رویکرد user-centered',
        showBadge: false,
      },
      {
        id: generateId(),
        type: 'link',
        enabled: true,
        title: 'نمونه‌کارها',
        url: 'https://example.com',
        icon: '🎨',
        badge: 'new',
        highlight: true,
        newTab: true,
        style: 'fill',
      },
      {
        id: generateId(),
        type: 'social',
        enabled: true,
        platforms: {
          instagram: 'sara_ui',
          linkedin: 'sara-mohammadi',
          github: 'saramohammadi',
        },
      },
      {
        id: generateId(),
        type: 'card',
        enabled: true,
        cardNumber: '6037991234567890',
        shaba: 'IR123456789012345678901234',
        accountHolder: 'سارا محمدی',
        bankName: 'ملی',
      },
      {
        id: generateId(),
        type: 'contact',
        enabled: true,
        phone: '09121234567',
        whatsapp: '',
        whatsappText: '',
        telegram: '',
      },
    ],
  },
  {
    id: 'shop',
    name: 'فروشگاه اینستاگرامی',
    icon: '🛍️',
    description: 'مناسب فروشگاه‌های آنلاین و اینستاگرامی',
    paletteId: 'peach',
    blocks: [
      {
        id: generateId(),
        type: 'profile',
        enabled: true,
        avatar: '',
        avatarShape: 'circle',
        name: 'فروشگاه ایناری',
        title: '',
        bio: 'ارسال به سراسر کشور',
        showBadge: false,
      },
      {
        id: generateId(),
        type: 'product',
        enabled: true,
        layout: 'grid',
        items: [
          { id: generateId(), image: '', name: 'کیف دستی چرم', price: 450000, link: '', badge: 'new' },
          { id: generateId(), image: '', name: 'کفش مجلسی', price: 320000, link: '', badge: 'sale' },
          { id: generateId(), image: '', name: 'کمربند چرم', price: 180000, link: '', badge: '' },
        ],
      },
      {
        id: generateId(),
        type: 'hours',
        enabled: true,
        schedule: [
          { day: 'شنبه', open: '10:00', close: '22:00', isOff: false },
          { day: 'یکشنبه', open: '10:00', close: '22:00', isOff: false },
          { day: 'دوشنبه', open: '10:00', close: '22:00', isOff: false },
          { day: 'سه‌شنبه', open: '10:00', close: '22:00', isOff: false },
          { day: 'چهارشنبه', open: '10:00', close: '22:00', isOff: false },
          { day: 'پنجشنبه', open: '10:00', close: '20:00', isOff: false },
          { day: 'جمعه', open: '', close: '', isOff: true },
        ],
      },
      {
        id: generateId(),
        type: 'contact',
        enabled: true,
        phone: '09129876543',
        whatsapp: '989129876543',
        whatsappText: 'سلام، سفارش دارم',
        telegram: '',
      },
      {
        id: generateId(),
        type: 'testimonial',
        enabled: true,
        items: [
          { id: generateId(), avatar: '', name: 'مریم ر.', text: 'کیفیت محصولات عالی بود، خیلی راضیم!', rating: 5 },
          { id: generateId(), avatar: '', name: 'زهرا ک.', text: 'ارسال سریع و بسته‌بندی تمیز', rating: 4 },
        ],
      },
    ],
  },
  {
    id: 'cafe',
    name: 'کافه/رستوران',
    icon: '☕',
    description: 'مناسب کافه‌ها، رستوران‌ها و فست‌فودها',
    paletteId: 'cafe',
    blocks: [
      {
        id: generateId(),
        type: 'profile',
        enabled: true,
        avatar: '',
        avatarShape: 'circle',
        name: 'کافه مادّی',
        title: '',
        bio: 'بهترین قهوه شهر',
        showBadge: false,
      },
      {
        id: generateId(),
        type: 'product',
        enabled: true,
        layout: 'slider',
        items: [
          { id: generateId(), image: '', name: 'اسپرسو', price: 80000, link: '', badge: '' },
          { id: generateId(), image: '', name: 'کاپوچینو', price: 120000, link: '', badge: '' },
          { id: generateId(), image: '', name: 'لاته', price: 110000, link: '', badge: 'new' },
          { id: generateId(), image: '', name: 'موکا', price: 130000, link: '', badge: '' },
        ],
      },
      {
        id: generateId(),
        type: 'hours',
        enabled: true,
        schedule: [
          { day: 'شنبه', open: '08:00', close: '23:00', isOff: false },
          { day: 'یکشنبه', open: '08:00', close: '23:00', isOff: false },
          { day: 'دوشنبه', open: '08:00', close: '23:00', isOff: false },
          { day: 'سه‌شنبه', open: '08:00', close: '23:00', isOff: false },
          { day: 'چهارشنبه', open: '08:00', close: '23:00', isOff: false },
          { day: 'پنجشنبه', open: '08:00', close: '00:00', isOff: false },
          { day: 'جمعه', open: '09:00', close: '00:00', isOff: false },
        ],
      },
      {
        id: generateId(),
        type: 'map',
        enabled: true,
        address: 'تهران، خیابان ولیعصر، نبش کوچه گل',
        lat: 35.6892,
        lng: 51.389,
      },
      {
        id: generateId(),
        type: 'gallery',
        enabled: true,
        images: ['', '', ''],
        columns: 3,
      },
    ],
  },
  {
    id: 'creator',
    name: 'تولیدکننده محتوا',
    icon: '🎥',
    description: 'مناسب یوتیوبرها، بلاگرها و تولیدکنندگان محتوا',
    paletteId: 'midnight',
    blocks: [
      {
        id: generateId(),
        type: 'profile',
        enabled: true,
        avatar: '',
        avatarShape: 'circle',
        name: 'امیر حسینی',
        title: 'یوتیوبر و تولیدکننده محتوا',
        bio: 'ساخت ویدیوهای آموزشی و سرگرمی',
        showBadge: true,
      },
      {
        id: generateId(),
        type: 'link',
        enabled: true,
        title: 'یوتیوب',
        url: 'https://youtube.com/@amirhossini',
        icon: '▶️',
        badge: '',
        highlight: true,
        newTab: true,
        style: 'fill',
      },
      {
        id: generateId(),
        type: 'link',
        enabled: true,
        title: 'حمایت مالی',
        url: 'https://example.com/donate',
        icon: '❤️',
        badge: 'special',
        highlight: false,
        newTab: false,
        style: 'soft',
      },
      {
        id: generateId(),
        type: 'video',
        enabled: true,
        platform: 'youtube',
        url: 'https://www.youtube.com/watch?v=example',
      },
      {
        id: generateId(),
        type: 'social',
        enabled: true,
        platforms: {
          youtube: 'amirhossini',
          instagram: 'amir_hosini',
          telegram: 'amirhossini',
        },
      },
      {
        id: generateId(),
        type: 'contact',
        enabled: true,
        phone: '',
        whatsapp: '989351234567',
        whatsappText: 'سلام، همکاری دارم',
        telegram: 'amirhossini',
      },
    ],
  },
  {
    id: 'salon',
    name: 'آرایشگاه',
    icon: '💇‍♀️',
    description: 'مناسب آرایشگاه‌ها و سالن‌های زیبایی',
    paletteId: 'strawberry',
    blocks: [
      {
        id: generateId(),
        type: 'profile',
        enabled: true,
        avatar: '',
        avatarShape: 'circle',
        name: 'سالن زیبایی ناز',
        title: 'سالن تخصصی زنانه',
        bio: 'خدمات تخصصی مو، ناخن و پوست',
        showBadge: false,
      },
      {
        id: generateId(),
        type: 'gallery',
        enabled: true,
        images: ['', '', ''],
        columns: 3,
      },
      {
        id: generateId(),
        type: 'hours',
        enabled: true,
        schedule: [
          { day: 'شنبه', open: '09:00', close: '20:00', isOff: false },
          { day: 'یکشنبه', open: '09:00', close: '20:00', isOff: false },
          { day: 'دوشنبه', open: '09:00', close: '20:00', isOff: false },
          { day: 'سه‌شنبه', open: '09:00', close: '20:00', isOff: false },
          { day: 'چهارشنبه', open: '09:00', close: '20:00', isOff: false },
          { day: 'پنجشنبه', open: '09:00', close: '21:00', isOff: false },
          { day: 'جمعه', open: '', close: '', isOff: true },
        ],
      },
      {
        id: generateId(),
        type: 'map',
        enabled: true,
        address: 'تهران، خیابان آزادی، مجتمع تجاری پارسیان، طبقه سوم',
        lat: 35.6792,
        lng: 51.389,
      },
      {
        id: generateId(),
        type: 'contact',
        enabled: true,
        phone: '02166778899',
        whatsapp: '989125554433',
        whatsappText: 'سلام، می‌خوام وقت بگیرم',
        telegram: '',
      },
    ],
  },
  {
    id: 'doctor',
    name: 'پزشک/مشاور',
    icon: '🩺',
    description: 'مناسب پزشکان، روانشناسان و مشاوران',
    paletteId: 'navy',
    blocks: [
      {
        id: generateId(),
        type: 'profile',
        enabled: true,
        avatar: '',
        avatarShape: 'circle',
        name: 'دکتر علی احمدی',
        title: 'روانشناس بالینی',
        bio: 'فوق‌لیسانس روانشناسی بالینی از دانشگاه تهران',
        showBadge: false,
      },
      {
        id: generateId(),
        type: 'hours',
        enabled: true,
        schedule: [
          { day: 'شنبه', open: '14:00', close: '20:00', isOff: false },
          { day: 'یکشنبه', open: '14:00', close: '20:00', isOff: false },
          { day: 'دوشنبه', open: '14:00', close: '20:00', isOff: false },
          { day: 'سه‌شنبه', open: '14:00', close: '20:00', isOff: false },
          { day: 'چهارشنبه', open: '14:00', close: '20:00', isOff: false },
          { day: 'پنجشنبه', open: '', close: '', isOff: true },
          { day: 'جمعه', open: '', close: '', isOff: true },
        ],
      },
      {
        id: generateId(),
        type: 'map',
        enabled: true,
        address: 'تهران، خیابان ولیعصر، بالاتر از میدان ونک، ساختمان پزشکان',
        lat: 35.7219,
        lng: 51.4114,
      },
      {
        id: generateId(),
        type: 'contact',
        enabled: true,
        phone: '02188776655',
        whatsapp: '',
        whatsappText: '',
        telegram: '',
      },
      {
        id: generateId(),
        type: 'faq',
        enabled: true,
        items: [
          {
            id: generateId(),
            question: 'آیا مشاوره آنلاین ارائه می‌دهید؟',
            answer: 'بله، مشاوره آنلاین از طریق واتساپ و تلگرام امکان‌پذیر است.',
          },
          {
            id: generateId(),
            question: 'نحوه رزرو وقت ویزیت چگونه است؟',
            answer: 'لطفاً از طریق واتساپ یا تماس تلفنی وقت خود را رزرو کنید.',
          },
        ],
      },
    ],
  },
  {
    id: 'teacher',
    name: 'مدرس/کوچ',
    icon: '🎓',
    description: 'مناسب مدرسین، کوچ‌ها و مربیان',
    paletteId: 'lavender',
    blocks: [
      {
        id: generateId(),
        type: 'profile',
        enabled: true,
        avatar: '',
        avatarShape: 'circle',
        name: 'نیلوفر کریمی',
        title: 'مدرس برنامه‌نویسی',
        bio: 'بیش از ۵ سال تجربه تدریس React و TypeScript',
        showBadge: false,
      },
      {
        id: generateId(),
        type: 'product',
        enabled: true,
        layout: 'grid',
        items: [
          { id: generateId(), image: '', name: 'دوره جامع React', price: 890000, link: '', badge: 'new' },
          { id: generateId(), image: '', name: 'دوره TypeScript', price: 650000, link: '', badge: '' },
          { id: generateId(), image: '', name: 'کارگاه پروژه محور', price: 450000, link: '', badge: 'sale' },
        ],
      },
      {
        id: generateId(),
        type: 'testimonial',
        enabled: true,
        items: [
          { id: generateId(), avatar: '', name: 'رضا م.', text: 'بهترین دوره‌ای بود که شرکت کردم، خیلی مفید بود!', rating: 5 },
          { id: generateId(), avatar: '', name: 'سمیرا ع.', text: 'توضیحات خیلی واضح و پروژه‌محور بود', rating: 5 },
        ],
      },
      {
        id: generateId(),
        type: 'faq',
        enabled: true,
        items: [
          {
            id: generateId(),
            question: 'آیا پیش‌نیاز خاصی برای دوره‌ها دارید؟',
            answer: 'آشنایی مقدماتی با HTML و CSS برای شروع کافی است.',
          },
          {
            id: generateId(),
            question: 'دوره‌ها به صورت ضبط‌شده هستند یا زنده؟',
            answer: 'دوره‌ها ضبط‌شده هستند و به صورت آنلاین قابل مشاهده‌اند.',
          },
        ],
      },
      {
        id: generateId(),
        type: 'contact',
        enabled: true,
        phone: '',
        whatsapp: '',
        whatsappText: '',
        telegram: 'niloofar_dev',
      },
    ],
  },
  {
    id: 'business-card',
    name: 'کارت ویزیت',
    icon: '📇',
    description: 'کارت ویزیت دیجیتال ساده و حرفه‌ای',
    paletteId: 'minimal',
    blocks: [
      {
        id: generateId(),
        type: 'profile',
        enabled: true,
        avatar: '',
        avatarShape: 'circle',
        name: 'محمد رضایی',
        title: 'مدیر پروژه',
        bio: '',
        showBadge: false,
      },
      {
        id: generateId(),
        type: 'social',
        enabled: true,
        platforms: {
          linkedin: 'mohammad-rezaei',
          instagram: 'm.rezaei',
        },
      },
      {
        id: generateId(),
        type: 'vcard',
        enabled: true,
        fullName: 'محمد رضایی',
        phone: '09123456789',
        email: 'm.rezaei@example.com',
        org: 'شرکت فناوری آینده',
        title: 'مدیر پروژه',
        address: 'تهران، خیابان ولیعصر',
      },
      {
        id: generateId(),
        type: 'email',
        enabled: true,
        email: 'm.rezaei@example.com',
        subject: 'سلام، می‌خواهم ارتباط برقرار کنم',
      },
      {
        id: generateId(),
        type: 'contact',
        enabled: true,
        phone: '09123456789',
        whatsapp: '989123456789',
        whatsappText: '',
        telegram: '',
      },
    ],
  },
]
